package rawdata;

public enum ParameterNumber {
            ROW_NUMBER,
            POTI_DRIVE,
            POTI_STEER,
            POTI_DIR,
            POTI_SIDE,
            BRAKE_PRESS,
            PUMP_L_PRESS,
            PUMP_R_PRESS,
            ATT_PUMP_PRESS,
            FAN_PUMP_PRESS,
            ENGINE_OIL_PRESS,
            GEAR_NUMBER,
            ENGINE_RPM,
            MOTOR_L_RPM,
            MOTOR_R_RPM,
            ENGINE_TEMP,
            HYD_OIL_TEMP,
            TURBO_TEMP,
            ENVIR_TEMP,
            CURR_P_FWD_L,
            CURR_P_FWD_R,
            CURR_P_REV_L,
            CURR_P_REV_R,
            CURR_M_L,
            CURR_M_R,
            CURR_FAN_PUMP,
            POTI_DIESEL,
            PEDAL_BRAKE,
            SAFETY_BUTTON,
            WORK_HOURS,
            TOTAL_QUANT
}
