public abstract class ParametersNumber {
    public static final int
            ROW_NUMBER = 0,
            POTI_DRIVE = 1,
            POTI_STEER = 2,
            POTI_DIR = 3,
            POTI_SIDE = 4,
            BRAKE_PRESS = 5,
            PUMP_L_PRESS = 6,
            PUMP_R_PRESS = 7,
            ATT_PUMP_PRESS = 8,
            FAN_PUMP_PRESS = 9,
            ENGINE_OIL_PRESS = 10,
            GEAR_NUMBER = 11,
            ENGINE_RPM = 12,
            MOTOR_L_RPM = 13,
            MOTOR_R_RPM = 14,
            ENGINE_TEMP = 15,
            HYD_OIL_TEMP = 16,
            TURBO_TEMP = 17,
            ENVIR_TEMP = 18,
            CURR_P_FWD_L = 19,
            CURR_P_FWD_R = 20,
            CURR_P_REV_L = 21,
            CURR_P_REV_R = 22,
            CURR_M_L = 23,
            CURR_M_R = 24,
            CURR_FAN_PUMP = 25,
            POTI_DIESEL = 26,
            PEDAL_BRAKE = 27,
            SAFETY_BUTTON = 28,
            WORK_HOURS = 29,
            TOTAL_QUANT = 30;
}
